# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    # "ds-test/=lib/solmate/lib/ds-test/src/",        # not currently in use
    "@chainlink/=node_modules/@chainlink/contracts/src/v0.8/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
aurora-test = "${AURORA_TEST_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "${SEPOLIA_API}" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", url = "${ARBITRUM_SEPOLIA_API}" }
aurora-test = { key = "QWERTY", url = "${AURORA_TEST_RPC_URL}" }


# forge script script/deploy_lockdrop.s.sol:Deploy --rpc-url ${ARBITRUM_SEPOLIA_RPC_URL} --private-key ${PRIVATE_KEY} --broadcast --verify --etherscan-api-key ${ARBITRUM_SEPOLIA_API} -vvvv


# Consuming Contract (consumer) == VRFv2Consumer

#   1. Deploy consumer (pass the Chainlink 'subscriptionId' as a constructor argument)  
#   2. Fund the consumer contract with LINK
#   2. Call fulfillRandomWords()
#   3. Confirm the event is emitted on etherscan
